// GENERADO por tools/build-icon-sprite.mjs — no editar a mano.
// La fuente de verdad es icons.json. Regenerar con: npm run icons

/** Nombres del set curado. Un icono fuera de esta lista no compila. */
export type NpIconName =
  | 'airplane'
  | 'arrow-left'
  | 'baby'
  | 'balloon'
  | 'bank'
  | 'bed'
  | 'bell'
  | 'briefcase'
  | 'bus'
  | 'cake'
  | 'calendar'
  | 'camera'
  | 'car'
  | 'car-simple'
  | 'caret-down'
  | 'caret-left'
  | 'caret-right'
  | 'champagne'
  | 'chart-bar'
  | 'chart-pie-slice'
  | 'check'
  | 'check-circle'
  | 'chef-hat'
  | 'church'
  | 'clock'
  | 'clock-countdown'
  | 'confetti'
  | 'cow'
  | 'credit-card'
  | 'crown-simple'
  | 'currency-eur'
  | 'device-mobile'
  | 'diamond'
  | 'disco-ball'
  | 'dots-six-vertical'
  | 'dots-three'
  | 'download-simple'
  | 'dress'
  | 'envelope'
  | 'eye'
  | 'eye-slash'
  | 'file-text'
  | 'first-aid'
  | 'fish'
  | 'flower'
  | 'fork-knife'
  | 'funnel'
  | 'game-controller'
  | 'gear'
  | 'gift'
  | 'grains'
  | 'hand-coins'
  | 'hand-heart'
  | 'heart'
  | 'images'
  | 'info'
  | 'leaf'
  | 'list'
  | 'list-checks'
  | 'lock-simple'
  | 'magnifying-glass'
  | 'map-pin'
  | 'money'
  | 'moon-stars'
  | 'music-notes'
  | 'navigation-arrow'
  | 'note-pencil'
  | 'palette'
  | 'pencil-simple'
  | 'plant'
  | 'playlist'
  | 'plus'
  | 'prohibit'
  | 'question'
  | 'seat'
  | 'share-network'
  | 'sliders-horizontal'
  | 'spinner-gap'
  | 'star'
  | 'steering-wheel'
  | 'sun'
  | 't-shirt'
  | 'table'
  | 'taxi'
  | 'tent'
  | 'train'
  | 'trash'
  | 'trophy'
  | 'upload-simple'
  | 'user'
  | 'user-plus'
  | 'users'
  | 'video-camera'
  | 'warning'
  | 'whatsapp-logo'
  | 'wheelchair'
  | 'wine'
  | 'x'
  | 'x-circle';

/** Peso como mecanismo de estado: regular inactivo, fill activo. */
export type NpIconWeight = 'regular' | 'fill';

/** Etiqueta por defecto de cada icono, para lectores de pantalla y selectores. */
export const NP_ICON_LABELS: Record<NpIconName, string> = {
  'church': "Ceremonia",
  'champagne': "Brindis",
  'fork-knife': "Banquete",
  'cake': "Tarta",
  'disco-ball': "Baile",
  'music-notes': "Música",
  'confetti': "Fiesta",
  'balloon': "Globos",
  'flower': "Flores",
  'camera': "Fotos",
  'video-camera': "Vídeo",
  'moon-stars': "Recena",
  'sun': "Exterior",
  'tent': "Carpa",
  'bus': "Autobús",
  'car': "Coche",
  'taxi': "Taxi",
  'train': "Tren",
  'airplane': "Avión",
  'car-simple': "Parking",
  'bed': "Alojamiento",
  'map-pin': "Ubicación",
  'navigation-arrow': "Cómo llegar",
  'wheelchair': "Accesibilidad",
  'clock': "Hora",
  'calendar': "Fecha",
  'users': "Grupo",
  'user': "Invitado",
  'user-plus': "Acompañante",
  'baby': "Niños",
  'heart': "Pareja",
  'diamond': "Anillos",
  'dress': "Vestido",
  't-shirt': "Dress code",
  'crown-simple': "Padrinos",
  'hand-heart': "Testigos",
  'steering-wheel': "Chófer",
  'leaf': "Vegetariano",
  'plant': "Vegano",
  'grains': "Sin gluten",
  'fish': "Pescado",
  'cow': "Carne",
  'first-aid': "Alergias",
  'chef-hat': "Catering",
  'wine': "Barra libre",
  'check-circle': "Confirmado",
  'x-circle': "No asiste",
  'clock-countdown': "Pendiente",
  'warning': "Atención",
  'info': "Información",
  'prohibit': "Bloqueado",
  'eye': "Visible",
  'eye-slash': "Oculto",
  'lock-simple': "Privado",
  'gift': "Regalo",
  'currency-eur': "Aportación",
  'credit-card': "Tarjeta",
  'bank': "Transferencia",
  'device-mobile': "Bizum",
  'money': "Efectivo",
  'hand-coins': "Recibido",
  'list-checks': "Checklist",
  'chart-bar': "Presupuesto",
  'chart-pie-slice': "Reparto",
  'briefcase': "Proveedores",
  'file-text': "Contrato",
  'table': "Mesas",
  'seat': "Asiento",
  'envelope': "Invitación",
  'whatsapp-logo': "WhatsApp",
  'share-network': "Compartir",
  'download-simple': "Exportar",
  'upload-simple': "Importar",
  'gear': "Configuración",
  'palette': "Diseño",
  'sliders-horizontal': "Módulos",
  'plus': "Añadir",
  'pencil-simple': "Editar",
  'trash': "Eliminar",
  'magnifying-glass': "Buscar",
  'funnel': "Filtrar",
  'dots-three': "Más acciones",
  'caret-down': "Desplegar",
  'caret-right': "Siguiente",
  'caret-left': "Anterior",
  'x': "Cerrar",
  'check': "Aceptar",
  'arrow-left': "Volver",
  'list': "Menú",
  'dots-six-vertical': "Arrastrar",
  'spinner-gap': "Cargando",
  'bell': "Avisos",
  'star': "Destacado",
  'question': "Preguntas frecuentes",
  'game-controller': "Quiz",
  'trophy': "Ranking",
  'images': "Galería",
  'note-pencil': "Libro de firmas",
  'playlist': "Playlist",
};
